/**
 * Risposte simulate per la chat demo (senza Edge Function).
 * Flusso: benvenuto → raccolta dati → riepilogo → conferma → bozza.
 */

export interface DemoReplyResult {
  text: string;
  draftText?: string;
}

export function getDemoReply(
  userMessage: string,
  messageCount: number,
  language: string
): DemoReplyResult {
  const lower = userMessage.toLowerCase().trim();
  const confirmWords = ['sì', 'si', 'yes', 'ja', 'oui', 'ok', 'conferma', 'procedi', 'continua'];

  const isConfirmation = confirmWords.some((w) => lower.includes(w));

  // Dopo 2+ messaggi utente, se conferma → genera bozza esempio
  if (messageCount >= 2 && isConfirmation) {
    const draft = getSampleDraft(language);
    return {
      text: getTranslation(language, 'demo_confirm'),
      draftText: draft,
    };
  }

  // Prima risposta: benvenuto
  if (messageCount === 0) {
    return { text: getTranslation(language, 'demo_welcome') };
  }

  // Risposte a domande tipiche
  if (
    lower.includes('lettera') ||
    lower.includes('letter') ||
    lower.includes('documento') ||
    lower.includes('document')
  ) {
    return { text: getTranslation(language, 'demo_letter_ask') };
  }

  if (
    lower.includes('scuola') ||
    lower.includes('school') ||
    lower.includes('assenze') ||
    lower.includes('absence')
  ) {
    return { text: getTranslation(language, 'demo_school') };
  }

  if (
    lower.includes('datore') ||
    lower.includes('employer') ||
    lower.includes('lavoro') ||
    lower.includes('work')
  ) {
    return { text: getTranslation(language, 'demo_employer') };
  }

  // Riepilogo dopo 2+ messaggi
  if (messageCount >= 2) {
    return { text: getTranslation(language, 'demo_summary') };
  }

  // Default
  return { text: getTranslation(language, 'demo_default') };
}

function getSampleDraft(lang: string): string {
  const templates: Record<string, string> = {
    en: `[Your name]
[Your address]
[City, Postal Code]

[Date]

[Recipient Name]
[Recipient address]

Subject: Sample Letter

Dear Sir or Madam,

Thank you for your correspondence. This is a sample draft generated by Lexora.

We kindly ask you to consider our request.

Yours sincerely,
[Your name]`,
    de: `[Ihr Name]
[Ihre Adresse]
[Ort, PLZ]

[Datum]

[Empfänger]
[Adresse des Empfängers]

Betreff: Musterbrief

Sehr geehrte Damen und Herren,

vielen Dank für Ihre Korrespondenz. Dies ist ein Musterentwurf von Lexora.

Wir bitten Sie, unsere Anfrage zu prüfen.

Mit freundlichen Grüßen
[Ihr Name]`,
    it: `[Nome e cognome]
[Indirizzo]
[Città, CAP]

[Data]

[Destinatario]
[Indirizzo destinatario]

Oggetto: Lettera campione

Egregi Signori,

La ringraziamo per la corrispondenza. Questa è una bozza campione generata da Lexora.

La preghiamo di considerare la nostra richiesta.

Cordiali saluti
[Firma]`,
  };
  return templates[lang] ?? templates.en;
}

function getTranslation(lang: string, key: string): string {
  const translations: Record<string, Record<string, string>> = {
    demo_welcome: {
      en: "Welcome! I'm Lexora, your AI legal assistant. Describe your situation (e.g. school absence, letter to employer) and I'll help you draft a formal letter. What do you need?",
      de: 'Willkommen! Ich bin Lexora, Ihr KI-Rechtsassistent. Beschreiben Sie Ihre Situation (z.B. Schulabwesenheit, Arbeitgeberanschreiben) und ich helfe Ihnen beim Verfassen eines formellen Schreibens. Was benötigen Sie?',
      it: 'Benvenuto! Sono Lexora, il tuo assistente legale AI. Descrivi la tua situazione (es. assenza scolastica, lettera al datore) e ti aiuterò a redigere una lettera formale. Di cosa hai bisogno?',
      fr: "Bienvenue ! Je suis Lexora, votre assistant juridique IA. Décrivez votre situation (ex. absence scolaire, lettre à l'employeur) et je vous aiderai à rédiger une lettre formelle. De quoi avez-vous besoin ?",
      es: '¡Bienvenido! Soy Lexora, tu asistente legal IA. Describe tu situación (ej. ausencia escolar, carta al empleador) y te ayudaré a redactar una carta formal. ¿Qué necesitas?',
    },
    demo_letter_ask: {
      en: "I can help you draft a formal letter. Tell me: who is the recipient (school, employer, landlord, authority)? And what's the main purpose?",
      de: 'Ich kann Ihnen beim Verfassen eines formellen Schreibens helfen. Sagen Sie mir: Wer ist der Empfänger (Schule, Arbeitgeber, Vermieter, Behörde)? Und was ist der Hauptzweck?',
      it: "Posso aiutarti a redigere una lettera formale. Dimmi: chi è il destinatario (scuola, datore, proprietario, ufficio)? E qual è lo scopo principale?",
    },
    demo_school: {
      en: "For a school absence letter I need: parent's name, child's name, school name, dates of absence, reason. Please provide these details.",
      de: 'Für ein Schreiben zur Schulabwesenheit benötige ich: Name des Erziehungsberechtigten, Name des Kindes, Schulname, Abwesenheitsdatum, Grund. Bitte geben Sie diese Angaben an.',
      it: "Per una lettera di giustificazione scolastica mi servono: nome del genitore, nome dello studente, scuola, date di assenza, motivo. Fornisci questi dettagli.",
    },
    demo_employer: {
      en: "For an employer letter I need: your name, your address, employer name, subject of the letter, and the details of your request. Please provide them.",
      de: 'Für ein Arbeitgeberschreiben benötige ich: Ihren Namen, Ihre Adresse, Arbeitgebername, Betreff und Einzelheiten Ihrer Anfrage. Bitte geben Sie diese an.',
      it: "Per una lettera al datore mi servono: tuo nome, indirizzo, nome datore, oggetto della lettera e dettagli della richiesta. Fornisci questi dati.",
    },
    demo_summary: {
      en: "I've noted the information. To generate the draft letter, please confirm with: Yes, Ok, or Proceed.",
      de: 'Ich habe die Angaben notiert. Um den Entwurf zu erstellen, bestätigen Sie bitte mit: Ja, Ok oder Weiter.',
      it: "Ho annotato le informazioni. Per generare la bozza, conferma con: Sì, Ok o Procedi.",
    },
    demo_confirm: {
      en: "Here's your draft. Register to save it to your Dashboard and create unlimited documents.",
      de: 'Hier ist Ihr Entwurf. Registrieren Sie sich, um ihn in Ihrem Dashboard zu speichern und unbegrenzt Dokumente zu erstellen.',
      it: 'Ecco la tua bozza. Registrati per salvarla nel Dashboard e creare documenti illimitati.',
    },
    demo_default: {
      en: "Please describe your situation in more detail: who is the letter for, and what do you want to achieve?",
      de: 'Bitte beschreiben Sie Ihre Situation genauer: An wen richtet sich das Schreiben und was möchten Sie erreichen?',
      it: "Descrivi meglio la situazione: a chi è rivolta la lettera e cosa vuoi ottenere?",
    },
  };

  const map = translations[key];
  if (!map) return key;
  return map[lang] ?? map.en ?? key;
}
